<?php

namespace Corncakes\MemberBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ChurchPersonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChurchPersonRepository extends EntityRepository
{
}
