<?php

namespace Corncakes\MemberBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PersonTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonTypeRepository extends EntityRepository
{
}
