church:
    path:     /
    defaults: { _controller: CorncakesMemberBundle:Church:index }

church_new:
    path:     /new
    defaults: { _controller: CorncakesMemberBundle:Church:new }

church_create:
    path:     /create
    defaults: { _controller: CorncakesMemberBundle:Church:create }
    methods:  POST

church_edit:
    path:     /edit/{id}
    defaults: { _controller: CorncakesMemberBundle:Church:edit }

church_update:
    path:     /update/{id}
    defaults: { _controller: CorncakesMemberBundle:Church:update }
    methods: [POST, PUT]